server:
  version: 0.0.1
  name: Muf
  site: "http://127.0.0.1:8088"
  tomcat:
    accesslog:
      enabled: true
      pattern: "access [%{yyyy-MM-dd'T'HH:mm.ss'Z'}t] %r %s %D %h"
    basedir: accesslog
  port: 8088
mail:
spring:
  datasource:
    hikari:
      maximum-pool-size: 20
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/myf
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

    show-sql: false
    hibernate:
      ddl-auto: update
security:
  jwt:
    token:
      secret-key: XG79AZCRs2WwDFXkRarcbEzV7J4YaeUBRcPv0Wb6aifgUKQ8ZAUtjoximqiGaip
      expire-length:         360000000
      header-string: Authorization
    claim:
      userAuthorities: aut
      userId: uid
    audience: "myf"
redis:
  host: localhost
  port: 6379
  database: 0
  prefix: "myf:1:"
httpclient:
  pool:
    max-size: 128
    per-route-size: 24
  timeout:
    connection: 60000
    socket: 240000
sms:
  sms-length: 6
  enabled: false
  smsc:
    url: https://smsc.ru/sys/send.php
    originator: MUF
    login: "krenog"
    password: "aseaf19450"
  test:
    code: 389153
    phone: 79999999999
com:
  krenog:
    filter:
      excluded:
        - /docs/**
        - /swagger-ui.html
        - /*
        - /webjars/**
        - /swagger-resources/**
        - /api/v1/auth/**
        - /api/v1/check-alive
        - /api/v1/check-alive/
        - /api/v1/user/check-phone
        - /api/v1/user/check-phone/
        - /api/v1/user/check-username
        - /api/v1/user/check-username/
